
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvoblhissmmdvaocbniy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2b2JsaGlzc21tZHZhb2Nibml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDk4NzMsImV4cCI6MjA1ODU4NTg3M30.mDPhySM_Ituf--jbAa70-f7QLyXqSa2uHm3J-gLlheI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
